name: Building and deploying 

on:
  push:
    branches:
      - main

  workflow_dispatch:


jobs:
  building:
    environment: development
    runs-on:  ubuntu-latest
    
    steps:
      - name: Checkout score repository
        uses: actions/checkout@v3

      - name: installing dependency
        run: npm ci

      - name: building 
        run: npm run build
      
        env: 
          VITE_PASSWORD: ${{ secrets.VITE_PASSWORD }}

      
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with: 
          name: build_files
          path: |
            dist

        
  deploying:
    needs: building
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: download the artifact
        uses: actions/download-artifact@v4
        with: 
          name: build_files
          path: ./dist

      - name: show contents
        run : ls -R ./dist

      - name: ls
        run : ls 






      

