name: Building and deploying 

on:
  push:
    branches:
      - main

  workflow_dispatch:


jobs:
  building:
    environment: development
    runs-on:  ubuntu-latest
    
    steps:
      - name: Checkout score repository
        uses: actions/checkout@v3

      - name: installing dependency
        run: npm ci

      - name: building 
        run: npm run build
      
        env: 
          VITE_PASSWORD: ${{ secrets.VITE_PASSWORD }}

      
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with: 
          name: build_files
          path: |
            dist

        
  deploying:
    needs: building
    environment: production
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
      AWS_SECRET_KEY: ${{ secrets.SECRET_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
    steps:
      - name: download the artifact
        uses: actions/download-artifact@v4
        with: 
          name: build_files
          path: ./dist


      - name: AWS Login
        run : | 
          aws configure set aws_access_key_id $AWS_ACCESS_KEY
          aws configure set aws_secret_access_key $AWS_SECRET_KEY
          aws configure set region $AWS_REGION
    
      - name: upload the artifact to s3 
        run:  aws s3 cp ./dist s3://${{ vars.AWS_BUCKET_NAME }}/ --recursive







      

